package com.xingqiu.server.payment.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.time.LocalDateTime;

@TableName("payment_orders")
public class PaymentOrder {

    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    private Long orderId;

    /** Unique outbound trade number, generated by our system. */
    private String outTradeNo;

    /** WeChat transaction ID, returned after payment success. */
    private String transactionId;

    /** Amount in cents (integer). Never use float/double for money. */
    private Long amountMinor;

    private String channel;

    private PaymentStatus status;

    private String prepayId;

    private String paySign;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    public enum PaymentStatus {
        PENDING,
        SUCCESS,
        FAILED,
        CLOSED
    }

    public PaymentOrder() {
        this.channel = "WECHAT_JSAPI";
        this.status = PaymentStatus.PENDING;
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Long getOrderId() { return orderId; }
    public void setOrderId(Long orderId) { this.orderId = orderId; }

    public String getOutTradeNo() { return outTradeNo; }
    public void setOutTradeNo(String outTradeNo) { this.outTradeNo = outTradeNo; }

    public String getTransactionId() { return transactionId; }
    public void setTransactionId(String transactionId) { this.transactionId = transactionId; }

    public Long getAmountMinor() { return amountMinor; }
    public void setAmountMinor(Long amountMinor) { this.amountMinor = amountMinor; }

    public String getChannel() { return channel; }
    public void setChannel(String channel) { this.channel = channel; }

    public PaymentStatus getStatus() { return status; }
    public void setStatus(PaymentStatus status) { this.status = status; }

    public String getPrepayId() { return prepayId; }
    public void setPrepayId(String prepayId) { this.prepayId = prepayId; }

    public String getPaySign() { return paySign; }
    public void setPaySign(String paySign) { this.paySign = paySign; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
