spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xingqiu_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.xingqiu.server: DEBUG
